### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by cru121** [dscorbett/view-link-as-text#1]
Thanks for this extension. How do I install it?

**Comment by dscorbett** [comment]
For now, you can temporarily install it by downloading it, going to about:debugging, clicking “Load Temporary Add-on”, and selecting manifest.json. A more permanent solution would be for me to sign it and publish it. Before I do that, though, I want to see if I can make it faster. There is a noticeable delay of around a second when opening some links.

You should still be able to use the original “View as Text” add-on, by the way. Firefox won’t remove support for XUL add-ons until November.

**Comment by dscorbett** [comment]
I have published this add-on on AMO: https://addons.mozilla.org/en-US/firefox/addon/view-link-as-text/. I ultimately decided against improving the speed: I am avoiding Firefox ≥57, so I no longer care.

**Comment by cru121** [comment]
Installed, works. Thanks!
